P12/rails5/config/routes.rb
Rails.application.routes.draw do
  get 'main/search'

  resources :bookinfos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

P12/rails5/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

P12/rails5/app/models/bookinfo.rb
class Bookinfo < ApplicationRecord
end

P12/rails5/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

P12/rails5/app/controllers/bookinfos_controller.rb
class BookinfosController < ApplicationController
  before_action :set_bookinfo, only: [:show, :edit, :update, :destroy]

  # GET /bookinfos
  # GET /bookinfos.json
  def index
    @bookinfos = Bookinfo.all
  end

  # GET /bookinfos/1
  # GET /bookinfos/1.json
  def show
  end

  # GET /bookinfos/new
  def new
    @bookinfo = Bookinfo.new
  end

  # GET /bookinfos/1/edit
  def edit
  end

  # POST /bookinfos
  # POST /bookinfos.json
  def create
    @bookinfo = Bookinfo.new(bookinfo_params)

    respond_to do |format|
      if @bookinfo.save
        format.html { redirect_to @bookinfo, notice: 'Bookinfo was successfully created.' }
        format.json { render :show, status: :created, location: @bookinfo }
      else
        format.html { render :new }
        format.json { render json: @bookinfo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookinfos/1
  # PATCH/PUT /bookinfos/1.json
  def update
    respond_to do |format|
      if @bookinfo.update(bookinfo_params)
        format.html { redirect_to @bookinfo, notice: 'Bookinfo was successfully updated.' }
        format.json { render :show, status: :ok, location: @bookinfo }
      else
        format.html { render :edit }
        format.json { render json: @bookinfo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookinfos/1
  # DELETE /bookinfos/1.json
  def destroy
    @bookinfo.destroy
    respond_to do |format|
      format.html { redirect_to bookinfos_url, notice: 'Bookinfo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bookinfo
      @bookinfo = Bookinfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bookinfo_params
      params.require(:bookinfo).permit(:acct, :title, :author, :edition, :publication)
    end
end

P12/rails5/app/controllers/main_controller.rb
class MainController < ApplicationController
  def search
  	@title=params[:title]
  	if @title == "" || @title == nil
  		@result = ""
	else
		@result = Bookinfo.where("title like ?","%"+@title+"%")
	end
  end
end

P12/rails5/app/helpers/application_helper.rb
module ApplicationHelper
end

P12/rails5/app/views/bookinfos/_form.html.erb
<%= form_for(bookinfo) do |f| %>
  <% if bookinfo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bookinfo.errors.count, "error") %> prohibited this bookinfo from being saved:</h2>

      <ul>
      <% bookinfo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :acct %>
    <%= f.number_field :acct %>
  </div>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :author %>
    <%= f.text_field :author %>
  </div>

  <div class="field">
    <%= f.label :edition %>
    <%= f.text_field :edition %>
  </div>

  <div class="field">
    <%= f.label :publication %>
    <%= f.text_field :publication %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

P12/rails5/app/views/bookinfos/edit.html.erb
<h1>Editing Bookinfo</h1>

<%= render 'form', bookinfo: @bookinfo %>

<%= link_to 'Show', @bookinfo %> |
<%= link_to 'Back', bookinfos_path %>

P12/rails5/app/views/bookinfos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bookinfos</h1>

<table>
  <thead>
    <tr>
      <th>Acct</th>
      <th>Title</th>
      <th>Author</th>
      <th>Edition</th>
      <th>Publication</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookinfos.each do |bookinfo| %>
      <tr>
        <td><%= bookinfo.acct %></td>
        <td><%= bookinfo.title %></td>
        <td><%= bookinfo.author %></td>
        <td><%= bookinfo.edition %></td>
        <td><%= bookinfo.publication %></td>
        <td><%= link_to 'Show', bookinfo %></td>
        <td><%= link_to 'Edit', edit_bookinfo_path(bookinfo) %></td>
        <td><%= link_to 'Destroy', bookinfo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bookinfo', new_bookinfo_path %>

P12/rails5/app/views/bookinfos/new.html.erb
<h1>New Bookinfo</h1>

<%= render 'form', bookinfo: @bookinfo %>

<%= link_to 'Back', bookinfos_path %>

P12/rails5/app/views/bookinfos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Acct:</strong>
  <%= @bookinfo.acct %>
</p>

<p>
  <strong>Title:</strong>
  <%= @bookinfo.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @bookinfo.author %>
</p>

<p>
  <strong>Edition:</strong>
  <%= @bookinfo.edition %>
</p>

<p>
  <strong>Publication:</strong>
  <%= @bookinfo.publication %>
</p>

<%= link_to 'Edit', edit_bookinfo_path(@bookinfo) %> |
<%= link_to 'Back', bookinfos_path %>

P12/rails5/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails5</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>